# Generated by Django 2.0 on 2018-12-01 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=128)),
                ('directory', models.CharField(max_length=128)),
                ('shell', models.CharField(default='/bin/bash', max_length=64)),
                ('useruid', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('groupGID', models.IntegerField()),
                ('groupName', models.CharField(max_length=64, unique=True)),
                ('groupPassword', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='additiongroup',
            field=models.ManyToManyField(blank=True, related_name='_user_additiongroup_+', to='linuxs.UserGroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linuxs.UserGroup', to_field='groupName'),
        ),
    ]
