# Generated by Django 2.0 on 2018-12-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linuxs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
