# Generated by Django 2.0 on 2018-12-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linuxs', '0002_auto_20181201_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, 'not exists'), (1, 'exists')], default=0),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='status',
            field=models.IntegerField(choices=[(0, 'not exists'), (1, 'exists')], default=0),
        ),
    ]
